### PR TITLE
Checking for pre-existing accounts from a different flow when using social connect

### PR DESCRIPTION
**Pull request by philippeluickx**
This fixes the following flow:
- user creates an account with normal signup
- user signs out
- user tries to login with a social account that has the same email address

Linked to https://github.com/Tivix/django-rest-auth/issues/78

### CODE REVIEW

**Comment by stantond** [comment]
I think django-allauth does this. Is it worth trying to use the functionality from there?

**Comment by philippeluickx** [comment]
@stantond - I had to go pretty deep in django-allauth and couldn't find a more elegant way to re-use functionality there. Could be I missed something though. Feel free to point me to the right direction.

**Comment by stantond** [comment]
No, I can't see how you'd reuse it. It's a shame these are separate projects

**Comment by philippeluickx** [comment]
Agreed on that. Or allauth becoming even more modular would help too...

**Comment by philippeluickx** [comment]
@danield-hyprbrands I am not very familiar with `throttle_classes`, but I am definitely open for suggestions.

**Comment by danield-hyprbrands** [comment]
Following the [docs](http://www.django-rest-framework.org/api-guide/throttling/) ,throttles are meant to be set via `throttle_classes`.
They also have an example there implementing `ScopedThrottleRate` which uses monkey patching to get the `scope_attr` from the view (by default `throttle_scope` is used as the `scope_attr`).
So, basicly, by setting the `throttle_scope` you are forcing everybody who uses the `ScopedThrottleRate` that is shown in the docs, to set the corresponding default rate, or in other words, you are enforcing the use of the default value of the `scope_attr`.

how about implementing your own scoped throttle, something along the lines of this:
```

from rest_framework.throttling import SimpleRateThrottle


class RestAuthScopedRateThrottle(SimpleRateThrottle):
    scope_attr = 'rest_auth_throttle_scope'

    def __init__(self):
        # Override the usual SimpleRateThrottle, because we can't determine
        # the rate until called by the view.
        pass

    def allow_request(self, request, view):
        # We can only determine the scope once we're called by the view.
        self.scope = getattr(view, self.scope_attr, None)

        if not self.scope:
            return True

        # Determine the allowed request rate as we normally would during
        # the `__init__` call.
        self.rate = self.get_rate()
        self.num_requests, self.duration = self.parse_rate(self.rate)

        # We can now proceed as normal.
        return super(RestAuthScopedRateThrottle, self).allow_request(request, view)


```

That way, if I don't want to throttle rest-auth, but just copy the `ScopedRateThrottle` from the docs, I can leave it untouched, and if I do want to throttle rest-auth, i'll add this class to my default throttle classes and set the according rate.

**Comment by philippeluickx** [comment]
@danield-hyprbrands Allright, I think I know why I am confused...

I simply updated my branch with the latest updates from upstream, one of which deals with throttling - https://github.com/Tivix/django-rest-auth/pull/215/commits/2a0fa1ab4eff07b5ec5169b7fe98a0f2c97a3e94 .

However, my fix does not come close to anything from throttling...
https://github.com/Tivix/django-rest-auth/pull/215/commits/569765639d59da69d18c6a63f41c3160500c4a15

**Comment by danield-hyprbrands** [comment]
Oh ok, I see, something got mixed up on the way. I'll repost my comment on the real commit. 
Sorry for the mix-up.

**Comment by philippeluickx** [comment]
No worries, glad to have it sorted out!

**Comment by mariodev** [comment]
@philippeluickx Can you please provide a test case for your changes? And also - thank you for following this issue from the very beginning!. This seems to be a very edge case scenario, so providing a test coverage would be very appreciated. Thanks.

**Comment by philippeluickx** [comment]
@mariodev Seems like there was already a test case that I could adapt.
Should be good now, let me know if I can help with anything else!

**Comment by dshinzie** [comment]
Any idea when this would be merged?

**Comment by Akay7** [comment]
@mariodev @philippeluickx 
this PR have any reason for be not merged yet?

**Comment by philippeluickx** [comment]
Added a check on "is_open_for_signup"
One problem though is that this check is also applied for social login. I am assuming that if "is_open_for_signup" is put to false, then people who already have a social account should still be able to signup. Not sure how to make the distinction though in the View?

**Comment by philippeluickx** [comment]
Cleaned up the PR in a new one:
https://github.com/Tivix/django-rest-auth/pull/367

**Pull request closed without merging**
