### PR TITLE
allows registration throttle control

### PR DESCRIPTION
**Pull request by vsevolod-kolchinsky**
allow registration throttle control using settings:

```python
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_RATES': {
        'anon': '6/m',
        'register_view':'1/h',
    },
}
```

### CODE REVIEW

**Comment by mariodev** [comment]
@vsevolod-kolchinsky Looks good. Can you please also update the docs accordingly, so the user is aware of the throttle option. Thanks.

**Comment by vsevolod-kolchinsky** [comment]
@mariodev Done, please check.

**Comment by mariodev** [comment]
@vsevolod-kolchinsky Thanks again!

**Comment by danield-hyprbrands** [comment]
@vsevolod-kolchinsky 
Following the [docs](http://www.django-rest-framework.org/api-guide/throttling/),
they also have an example there implementing `ScopedRateThrottle` which uses monkey patching to get the `scope_attr` from the view (by default `throttle_scope` is used as the `scope_attr`).
So, basicly, by setting the `throttle_scope` you are forcing everybody who uses the `ScopedRateThrottle` that is shown in the docs, to change `scope_attr` if they don't need to throttle rest-auth.

how about implementing your own scoped throttle, something along the lines of this:
```

from rest_framework.throttling import SimpleRateThrottle


class RestAuthScopedRateThrottle(SimpleRateThrottle):
    scope_attr = 'rest_auth_throttle_scope'

    def __init__(self):
        # Override the usual SimpleRateThrottle, because we can't determine
        # the rate until called by the view.
        pass

    def allow_request(self, request, view):
        # We can only determine the scope once we're called by the view.
        self.scope = getattr(view, self.scope_attr, None)

        if not self.scope:
            return True

        # Determine the allowed request rate as we normally would during
        # the `__init__` call.
        self.rate = self.get_rate()
        self.num_requests, self.duration = self.parse_rate(self.rate)

        # We can now proceed as normal.
        return super(RestAuthScopedRateThrottle, self).allow_request(request, view)


```

That way, if I don't want to throttle rest-auth, but just use the `ScopedRateThrottle` from the docs, I can leave it untouched, and if I do want to throttle rest-auth, i'll add this class to my default throttle classes and set the according rate.

**Comment by maxim-kht** [comment]
@danield-hyprbrands Thank you for your feedback! 

It is correct, if somebody is using `rest_framework.throttling.ScopedRateThrottle` but only for their own views, they will encounter `ImproperlyConfigured: No default throttle rate set for 'register_view' scope` error, when accessing register_view. This does put a constraint, might lead to additional debugging time, and they will have to set `'register_view': None` in their settings eventually. 

I think the better way to use Django REST Framework throttle control is to subclass RegisterView and add `throttle_scope` there. It will also make it easier to debug as well.

**Pull request merged**
