### PR TITLE
Add django.contrib.sites to INSTALLED_APPS

### PR DESCRIPTION
**Pull request by hkraal**
As requested in https://github.com/Tivix/django-rest-auth/issues/218 hereby the PR to include ``django.contrib.sites`` in the installation instructions.

### CODE REVIEW

**Comment by Akay7** [comment]
When include django.contrib.sites in installed apps, also you must setup SITE_ID =

**Comment by hkraal** [comment]
@Akay7 Right, fixed that with a new commit. Let me know if all is in order according to you and I'll rebase  and squash before you merge

**Comment by Akay7** [comment]
@hkraal really you can set any number to SITE_ID. But that's okay, anyway who must set different numbers to SITE_ID they will know what they do.

**Comment by mariodev** [comment]
@hkraal Looks good. Please do a squash and then I'll merge it into master. Thanks!

**Comment by hkraal** [comment]
@mariodev I've squashed my commits and rebased master onto my branch so it should be a clean FF merge!

**Pull request merged**
