### PR TITLE
A few fixes, cleaned up in nice commits

### PR DESCRIPTION
**Pull request by philippeluickx**
Based on my own needs and a few issues.

### CODE REVIEW

**Comment by ClairePhila** [comment]
@philippeluickx Thank you for your great work! Did you get it work with https://github.com/sahat/satellizer?
I tried it with the following satellizer settings (DRF app running on localhost), but it didn't work:

    $authProvider.facebook({
            url: 'http://127.0.0.1:8000/rest-auth/facebook/',
            clientId: 'MY-FB-CLIENT-ID'
        });

**Comment by philippeluickx** [comment]
Hey @ClairePhila !
I got everything running smoothly on my side. However I have a few more settings, something here might point you in the right direction?

    $authProvider.tokenName = 'key';
    $authProvider.authToken = 'Token';
    $authProvider.baseUrl = apiUrl;
    $authProvider.loginUrl = 'auth/login/';
    $authProvider.signupUrl = 'auth/registration/';
    $authProvider.loginRedirect = '';

    $authProvider.facebook({
      clientId: facebookClientId,
      url: 'auth/facebook/',
    });

**Comment by ClairePhila** [comment]
Hi @philippeluickx !
Thank you very much for your help, but this doesn't work for me either. In your case, is the redirect ('auth/facebook/') calling the client (satellizer) or the server (django-rest-auth)? I do still not get the coincidence of satellizer and django-rest-auth, because both a django user has to be created and this user has to be set in satellizer. 

Do you no a sample project using both technologies?

**Comment by philippeluickx** [comment]
The redirect needs to be set on both the frontend (satellizer) and backend, the same value. Check out the docs in the code at https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/registration/views.py#L98

Make sure your facebook settings are correct too.

**Comment by ClairePhila** [comment]
Thank you again, @philippeluickx !
Now, it almost seems to work, despite of the fact that the Facebook redirect is a GET to '/auth/facebook'. But since the SocialLoginView is a LoginView, it only accepts POST requests (https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/views.py#L52). I'm so sorry, but I think I still didn't get it right.

**Comment by philippeluickx** [comment]
The redirect value is just a common agreed value. If I remember correctly, it does not actually do a redirect to that page.

My front-end is pretty simple, this should work:

```javascript
    /**
    * @name authenticate
    * @desc authenticate a user with a social provider
    * @memberOf application.authentication.controllers.LoginController
    */
    function authenticate(provider) {
      $auth.authenticate(provider)
      .then(function(response) {
          $state.transitionTo('home');
      })
      .catch(function(response) {
      });
    };
```

I assume there is a 2-step process:
1. GET the code from FB
2. POST the code to your own backend.

**Pull request merged**
