### PR TITLE
Resend confirmation email

### PR DESCRIPTION
**Pull request by mbaragiola**
When trying to login using an unverified email address, resend confirmation email.

### CODE REVIEW

**Comment by mbaragiola** [comment]
Any news?

**Comment by tanoabeleyra** [comment]
Almost one year has passed and this still open, why? This feature is really needed.

**Comment by morenoh149** [comment]
@virgilio if splitting the PR is required, how should it be split? by commit or by changes?

**Comment by frossigneux** [comment]
I really need this feature too! Please merge it

**Comment by brunobarretofreitas** [comment]
I've created another pull request with another approach.  #530 
In this pull request, whenever an unverified user try to login, an email will be sent. So, if the user tries to login 5 times consecutively, 5 emails will be sent.
In my approach, I've created an endpoint for resending a verification email, so it can be managed better by the application owner. Please, check it out and vote :)

**Comment by BarnabasSzabolcs** [comment]
Hi, 
as a user of rest-auth, thanks for the contribution! 
This repo is not maintained anymore, so the development moved to dj-rest-auth. (reference: https://github.com/Tivix/django-rest-auth/issues/568)
It may be best, if you move this PR there. (and upgrade to using dj_rest_auth)

new repo link: https://github.com/jazzband/dj-rest-auth (I'm not the upkeeper of that repo, it just makes sense for me to help you merge your PR)

Many Thanks,
Barney

**Comment by mbaragiola** [comment]
Closing due to inactivity.

**Pull request closed without merging**
