### PR TITLE
add 'id' field to UserDetailsSerializer

### PR DESCRIPTION
**Pull request by agustinaliagac**

### CODE REVIEW

**Comment by Akay7** [comment]
for what??

**Comment by agustinaliagac** [comment]
when I register a new user using /rest-auth/registration/ it only returns the Token key. After this, I would like to have the current user data (username, email, id) and I call GET /rest-auth/user/ for that. I noticed I wasn't getting the user id (which I need for some custom business logic in my project), and since this is a minor but useful change I made this PR.

**Comment by Akay7** [comment]
@agustinaliagac  you can setup USER_DETAILS_SERIALIZER  in settings.py. I though that not good idea send ID of user in details. No one must know how you save user and witch 'id' it have.(security reason)

**Comment by agustinaliagac** [comment]
@Akay7 Awesome. Thanks, I'll take a look at it.

**Comment by mjaworski** [comment]
Agreed with @Akay7 , use USER_DETAILS_SERIALIZER if needed.

**Pull request closed without merging**
