### PR TITLE
Replaced request.DATA with request.data for compatibility with DRF 3.2

### PR DESCRIPTION
**Pull request by alacritythief**
In the latest version of DRF 3.2, `request.DATA` has been deprecated in favor of `request.data`. I've made this minor change to make it work with one of my projects.

### CODE REVIEW

**Comment by illing2005** [comment]
Unfortunately this doesn't fix all.
`request.FILES` is also deprecated in favor of `request.files`
And the registration uses `all_auth` SignupForm. And somewhere there `django.view.generics.edit` is used where `request.FILES` is used.

**Comment by alacritythief** [comment]
The `request.data` fix is on the django-rest-auth side of things. There is no code in django-rest-auth with `request.FILES` and `request.QUERY_PARAMS` that need to be fixed.

The issue is with `request.FILES` is in core Django, located in `django/views/generic/edit.py` line 88:

```
85	        if self.request.method in ('POST', 'PUT'):
86	            kwargs.update({
87	                'data': self.request.POST,
88	                'files': self.request.FILES,
89	            })
90	        return kwargs
```

I might have to hack together a fix in DRF 3.2 in my work projects to use the downcase versions whenever they are called in upcase.

**Comment by alacritythief** [comment]
Latest master of DRF fixes this:
https://github.com/tomchristie/django-rest-framework/issues/3239

**Comment by illing2005** [comment]
:+1:

**Pull request merged**
