### PR TITLE
Make email in password reset serializer Case unsensetive

### PR DESCRIPTION
**Pull request by Akay7**
if user input correct email but in wrong case.
For example use Capital letters instead Lover case or mix them, he will get error. But really DB exist his email.

### CODE REVIEW

**Comment by Akay7** [comment]
Excuse  me, at which version of rest-auth in pip it will work well?

**Comment by mariodev** [comment]
We're also working on other fixes. It should be released as 0.6.1 in few days. 
Thank you for noticing and fixing this bug :pray:

**Comment by Akay7** [comment]
Thanks to you, that's is very useful module.
Maybe you also needed changes in auth-serializer for authentication  by email and password(when application don't use all-auth)? I can make this changes and write tests for it on weekend, if you need it.

**Comment by mariodev** [comment]
@Akay7 This would awesome!. Please do..

**Comment by Akay7** [comment]
@mariodev I'm make that https://github.com/Tivix/django-rest-auth/pull/141

**Pull request merged**
