### PR TITLE
docs: Update registration install command for zsh

### LINKED ISSUE #402: pip install django-rest-auth[with_social] not working
I'm trying to integrate django-rest-auth with django-allauth to support social login.
So I tried the following, after the reading the doc

```pip install django-rest-auth[with_social]```
 
But I could not install the package with the error message returning 

`zsh: no matches found: django-rest-auth[with_social]`

Any ideas why this happens? Thanks.

### PR DESCRIPTION
**Pull request by erdaltsksn**
why: The zsh cannot process [] character correctly.

issue: close #402

### CODE REVIEW

**Comment by BarnabasSzabolcs** [comment]
Hi, 
as a user of rest-auth, thanks for the contribution! 
This repo is not maintained anymore, so the development moved to dj-rest-auth. (reference: https://github.com/Tivix/django-rest-auth/issues/568)
It may be best, if you move this PR there. (and upgrade to using dj_rest_auth)

new repo link: https://github.com/jazzband/dj-rest-auth (I'm not the upkeeper of that repo, it just makes sense for me to help you merge your PR)

Many Thanks,
Barney

**Comment by erdaltsksn** [comment]
Thank you for warning.

I think a note in **README** could be wonderful for future references.

**Comment by BarnabasSzabolcs** [comment]
I agree.
The thing is that the maintainers of this repo seem to have vanished and nobody seems to have access to do that. (As far as I can see from the discussion)

**Comment by erdaltsksn** [comment]
ref: https://github.com/jazzband/dj-rest-auth/pull/74

**Pull request closed without merging**
