### PR TITLE
Checking for pre-existing accounts

### PR DESCRIPTION
**Pull request by philippeluickx**
This deals with edge cases

### CODE REVIEW

**Comment by brunosmartin** [comment]
Please, merge this like there is no tomorrow!!! This is a serious bug in this incredible project.

**Comment by EvanZ** [comment]
Any updates on this?

**Comment by maxim-kht** [comment]
@EvanZ This change is merged and included in latest version.

**Comment by EvanZ** [comment]
Ah, I upgraded to 0.9.3 and now I'm getting 400 errors. "Incorrect value" in a non_field_errors. Any idea what that means? My request hasn't changed:

```
return axios.post('/rest-auth/facebook/', {
                access_token: payload.key
            })
```

**Pull request merged**
