### PR TITLE
Fixed issues #159 #164 CSRF Failed

### PR DESCRIPTION
**Pull request by girishkumarkh**
Fixes: https://github.com/Tivix/django-rest-auth/issues/159 and https://github.com/Tivix/django-rest-auth/issues/164

### CODE REVIEW

**Comment by Akay7** [comment]
What about if I would like use few different authentication systems? For example: Session and Token based.

**Comment by girishkumarkh** [comment]
Good point! I am not sure whether everything works fine if we enable both token and session auth. Needs checking.

**Comment by mjaworski** [comment]
Choice to use Token vs Session auth is up to the developer of the app, what should be done is investigate the issue and fix the CSRF error for Token auth when Session auth is also enabled.

**Comment by Akay7** [comment]
@girishkumarkh its work fine, but you must add one more auth-view for token auth

`
from rest_framework.authentication import TokenAuthentication
from rest_auth.registration.views import LoginView

class LoginViewCustom(LoginView):
    authentication_classes = (TokenAuthentication,)
`

**Pull request closed without merging**
