### PR TITLE
Rewrite registration logic

### PR DESCRIPTION
**Pull request by ron8mcr**
Make registration view more django_rest_framework way. Also add serializer for email verification

### CODE REVIEW

**Comment by akarambir** [comment]
:+1: Using this PR in my project

**Comment by Akay7** [comment]
Not all Django apps use allauth.

**Comment by ron8mcr** [comment]
@Akay7, `rest_auth.registration` is *optional* module (see [docs](http://django-rest-auth.readthedocs.org/en/latest/installation.html#registration-optional))
Also current solution is built on allauth's Signup `form` instead of `serializer`.
Main festure of this PR - make signing up with replacable serializer. Lateley it can be updated to be independent of `allauth`

**Comment by Akay7** [comment]
@ron8mcr thx for link, I'm not use registration in my project, but give to user ability rewrite serialize for registration is good opportunity.  I just don't understand why you prefer just one password field?

**Comment by ron8mcr** [comment]
IMHO, this kind of validation should be at the client's side - mobile app, SPA or anything else

**Comment by Akay7** [comment]
@ron8mcr if you want prototype app in short time interval, I though more better if that will be on server. In anyway if you concentrate on client side you can send same data in two fields, and have all validation on client, that's not too much hard. But if device on which you develop app have limited resources or for old browser, more better if validation like this will be on server side.
ps: That's my IMHO

**Comment by mariodev** [comment]
Thank you @ron8mcr :pray:  This PR will be merged very shortly.

**Comment by mariodev** [comment]
@Akay7 Thank you for all your comments. I agree with @ron8mcr on the one password solution. Registration flow should be as fast and easy as possible. You can always extend the serializer to add password confirmation on the backend (although it should be implemented on the client side as @ron8mcr mentioned).

**Comment by Akay7** [comment]
@mariodev This commit can broke some functionality which was be written for last version of Rest-auth. I hope you will not getting too much unhappy users.

**Comment by mariodev** [comment]
@ron8mcr Seems like @Akay7's got a point. Maybe a better idea would be to add optional settings flag to use password confirmation (with default value tuned on, so not to break functionality).
Any thoughts?

**Comment by ron8mcr** [comment]
@mariodev we can use setting `ACCOUNT_SIGNUP_PASSWORD_VERIFICATION` from `allauth` [settings](http://django-allauth.readthedocs.org/en/latest/configuration.html).
But what would be the name of main field? `password1` or `password`? It would be strange to use field `password1` without second field for confirmation. IMHO, using one field for registration is much simplier and more REST API way.
Users doesn't have to update this app if they do not want to change their code. You just should mention this kind of change for new version of app.
This is my IMHO.

**Comment by Akay7** [comment]
@ron8mcr You use for your app <password> field, before it use <password1> and <password2> fields. You can just have to look which fields sent in request and depends on that information you can choose type of verification password. 
If you will update it for using without ACCOUNT_SIGNUP_PASSWORD_VERIFICATION flag, that let users update front-end part without changing any other settings and it will be fully functionally on both types of front-end side. And that let users of rest-auth "lazy update" they applications, or just update version of rest-auth.

**Pull request closed without merging**
