### PR TITLE
fix import complete_social_login

### PR DESCRIPTION
**Pull request by asudoma**

### CODE REVIEW

**Comment by jasinai** [comment]
:+1:

**Comment by Akay7** [comment]
Registration is optional only for projects with allauth, or not?

**Comment by mariodev** [comment]
@Akay7 Allauth is required if you're using built-in DRA registration.

**Comment by Akay7** [comment]
@mariodev if it required, how importing complete_social_login can raise error?

**Comment by Akay7** [comment]
For which reason needed that statement?
` if 'allauth.socialaccount' in settings.INSTALLED_APPS: `
That is registration module, how it can be useful without allauth?

**Comment by mariodev** [comment]
@Akay7 You can override this serializer class and avoid using `complete_social_login` (for whatever reason). This allows to avoid unnecessary exceptions.
Please provide your own PR if you think this can be resolved any other way.

**Pull request merged**
