### PR TITLE
Update Travis CI config to run on Python 3.5.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by frewsxcv** [comment]
Is Travis not enabled for this repository?

**Comment by mariodev** [comment]
@frewsxcv Can you merge master please?. There's been some changes that brakes your branch. Thanks.

**Comment by frewsxcv** [comment]
@mariodev Just rebased on top of `master`. It appears Travis CI is not enabled for this repository, despite there being a `.travis.yml` file.

**Comment by frewsxcv** [comment]
It appears that Travis *is* enabled, but GitHub isn't showing the status for some reason. Tests pass now.

https://travis-ci.org/Tivix/django-rest-auth/builds/135747105

**Comment by mariodev** [comment]
@frewsxcv Thanks again! 👍

**Pull request merged**
