### PR TITLE
Django 1.8 fixes

### PR DESCRIPTION
**Pull request by Antwan86**
This PR removes a warning due to the usage of `django.utils.importlib` which is [deprecated](https://docs.djangoproject.com/en/dev/releases/1.7/#django-utils-dictconfig-django-utils-importlib).
*Includes backward compatibility for Django 1.5 & 1.6 + Python 2.6.*

Also please consider bumping the module version as Django 1.8 is the current stable branch now.

### CODE REVIEW

**Comment by mjaworski** [comment]
The python version check doesn't seem to work, since builds on 2.6 fail:
https://travis-ci.org/Tivix/django-rest-auth/builds/58929927

**Comment by Antwan86** [comment]
Ok it should be perfect now :)

**Comment by Antwan86** [comment]
Thanks for the good work on this module ! When will you bump the version number ?

**Comment by mjaworski** [comment]
Just before releasing it, have to consult a colleague when exactly that will be.

**Pull request merged**
